name: Check & Run formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install Black
      run: |
        pip install black
    - name: Check 
      run: |
        black --check src tests
      # if: failure()
      # run: |
      #   black src tests
      # - uses: EndBug/add-and-commit@v7
      #   with:
      #     default_author: github_actions
