name: Update docs and formatting 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Upgrade pip & install pdoc
      run: |
        python -m pip install --upgrade pip
        pip install pdoc black
    - name: Run pdoc and black and commit
      run: |
        black --line-length 140 .
        pdoc --math -o docs rat
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
