name: Check & Run formatting on merge to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Upgrade pip & install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run formatter and commit
      run: |
        black --line-length 140 .
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
