name: Integration tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install .
    - name: Run integration tests
      run: |
        pip install pytest
        pytest tests/integration