name: Format code & run tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Upgrade pip & install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run formatter and commit
      run: |
        black .
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions

  build:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package and pytest
      run: |
        pip install .
        pip install pytest
    - name: Run unit tests
      run: |
        pytest tests/unit
    - name: Run integration tests
      run: |
        pytest tests/integration